In [1]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
import pandas as pd

data = pd.read_csv('./Data/final_data.csv')
data.head()

Unnamed: 0  Unnamed: 0.1  capacity_bytes        date  days_before_failure  \
0           0             0    4.000787e+12  2018-01-01                312.0   
1           1             1    4.000787e+12  2018-01-02                311.0   
2           2             2    4.000787e+12  2018-01-03                310.0   
3           3             3    4.000787e+12  2018-01-04                309.0   
4           4             4    4.000787e+12  2018-01-05                308.0   

   failure        model serial_number  smart_10_raw  smart_11_raw  ...  \
0        0  ST4000DM000      S301GMGW     -0.012181     -0.118116  ...   
1        0  ST4000DM000      S301GMGW     -0.012181     -0.118116  ...   
2        0  ST4000DM000      S301GMGW     -0.012181     -0.118116  ...   
3        0  ST4000DM000      S301GMGW     -0.012181     -0.118116  ...   
4        0  ST4000DM000      S301GMGW     -0.012181     -0.118116  ...   

   smart_251_raw  smart_252_raw  smart_254_raw  smart_2_raw  smart_3_raw  \
0            NaN            NaN            NaN          NaN          NaN   
1            NaN            NaN            NaN          NaN          NaN   
2            NaN            NaN            NaN          NaN          NaN   
3            NaN            NaN            NaN          NaN          NaN   
4            NaN            NaN            NaN          NaN          NaN   

   smart_4_raw  smart_5_raw  smart_7_raw  smart_8_raw  smart_9_raw  
0          NaN          NaN          NaN          NaN          NaN  
1          NaN          NaN          NaN          NaN          NaN  
2          NaN          NaN          NaN          NaN          NaN  
3          NaN          NaN          NaN          NaN          NaN  
4          NaN          NaN          NaN          NaN          NaN  

[5 rows x 65 columns]

In [2]:
data = data.fillna(0)
from collections import Counter
#ounter(list(data.loc[:, 'days_before_failure'].values))
#final_data = data[data['days_before_failure'] != 119]
final_data = data[data['days_before_failure'] >= -1.0]
final_data[final_data['days_before_failure'] == 0] = 1000
final_data[final_data['days_before_failure'] == -1] = 0
Counter(list(final_data.loc[:, 'days_before_failure'].values))

C:\Users\admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
C:\Users\admin\Anaconda3\lib\site-packages\pandas\core\indexing.py:494: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s
C:\Users\admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://

Counter({312.0: 318,
         311.0: 330,
         310.0: 340,
         309.0: 355,
         308.0: 360,
         307.0: 359,
         306.0: 364,
         305.0: 365,
         304.0: 372,
         303.0: 389,
         302.0: 394,
         301.0: 404,
         300.0: 415,
         299.0: 417,
         298.0: 423,
         297.0: 433,
         296.0: 437,
         295.0: 445,
         294.0: 452,
         293.0: 458,
         292.0: 461,
         291.0: 467,
         290.0: 478,
         289.0: 472,
         288.0: 479,
         287.0: 485,
         286.0: 489,
         285.0: 499,
         284.0: 508,
         283.0: 514,
         282.0: 519,
         281.0: 527,
         280.0: 534,
         279.0: 537,
         278.0: 541,
         277.0: 553,
         276.0: 560,
         275.0: 570,
         274.0: 580,
         273.0: 592,
         272.0: 593,
         271.0: 600,
         270.0: 599,
         269.0: 601,
         268.0: 610,
         267.0: 619,
         266.0: 631,
         265.

In [3]:

# Excluding days_before_failure, failure, model, serial_number, index, and date from the training dataset
train = final_data.loc[:, data.columns != 'days_before_failure']
train = train.loc[:, train.columns != 'failure']
train = train.loc[:, train.columns != 'model']
train = train.loc[:, train.columns != 'serial_number']
train = train.iloc[:, 4:]

# Feature Selection: 5, 9, 187, 188, 193, 194, 197, and 198, 241, 242
train = train.fillna(0)
train = train[['smart_5_raw','smart_9_raw','smart_187_raw',
       'smart_188_raw','smart_193_raw','smart_194_raw',
       'smart_197_raw','smart_198_raw','smart_241_raw','smart_242_raw']]
pd.set_option('max_columns', 300)
display(train.head())

X = train.iloc[:, :].values
y = final_data.loc[:, 'days_before_failure'].values


smart_5_raw  smart_9_raw  smart_187_raw  smart_188_raw  smart_193_raw  \
0          0.0          0.0      -0.014346      -0.067059       0.547236   
1          0.0          0.0      -0.014346      -0.067059       0.547236   
2          0.0          0.0      -0.014346      -0.067059       0.547236   
3          0.0          0.0      -0.014346      -0.067059       0.547253   
4          0.0          0.0      -0.014346      -0.067059       0.559559   

   smart_194_raw  smart_197_raw  smart_198_raw  smart_241_raw  smart_242_raw  
0       0.085230      -0.019682      -0.019178            0.0            0.0  
1      -0.067508      -0.019682      -0.019178            0.0            0.0  
2       0.237968      -0.019682      -0.019178            0.0            0.0  
3       0.085230      -0.019682      -0.019178            0.0            0.0  
4       0.085230      -0.019682      -0.019178            0.0            0.0

In [7]:
"""from imblearn.over_sampling import SMOTE

class_num = dict.fromkeys(y)
for cl in class_num:
    class_num[cl] = 10000
del class_num[0.0]

sm = SMOTE(random_state=2, sampling_strategy=class_num, n_jobs=-1)
X_train_res, y_train_res = sm.fit_sample(X_train, y_train.ravel())
print(len(X_train_res))"""

In [4]:
# Under Sample
from imblearn.under_sampling import RandomUnderSampler
rus = RandomUnderSampler(return_indices=True, sampling_strategy= {1000.0:100000})
X_rus, y_rus, id_rus = rus.fit_sample(X, y)
print(X_rus)
print(Counter(list(y_rus)))

[[   0.    0.    0. ...    0.    0.    0.]
 [   0.    0.    0. ...    0.    0.    0.]
 [   0.    0.    0. ...    0.    0.    0.]
 ...
 [1000. 1000. 1000. ... 1000. 1000. 1000.]
 [1000. 1000. 1000. ... 1000. 1000. 1000.]
 [1000. 1000. 1000. ... 1000. 1000. 1000.]]
Counter({1000.0: 100000, 0.0: 3162, 1.0: 3078, 2.0: 3045, 3.0: 3018, 4.0: 2984, 5.0: 2943, 6.0: 2908, 7.0: 2888, 8.0: 2869, 9.0: 2860, 10.0: 2851, 11.0: 2828, 12.0: 2808, 13.0: 2790, 14.0: 2776, 15.0: 2758, 16.0: 2752, 17.0: 2732, 18.0: 2708, 19.0: 2689, 20.0: 2673, 21.0: 2653, 22.0: 2638, 23.0: 2626, 24.0: 2623, 25.0: 2601, 26.0: 2585, 27.0: 2550, 28.0: 2540, 29.0: 2527, 30.0: 2521, 31.0: 2514, 32.0: 2508, 33.0: 2505, 35.0: 2499, 34.0: 2496, 36.0: 2489, 37.0: 2470, 38.0: 2462, 39.0: 2449, 40.0: 2435, 41.0: 2420, 42.0: 2415, 43.0: 2397, 45.0: 2388, 46.0: 2386, 44.0: 2380, 48.0: 2372, 47.0: 2369, 49.0: 2354, 50.0: 2343, 51.0: 2332, 52.0: 2313, 53.0: 2306, 54.0: 2288, 55.0: 2275, 56.0: 2274, 57.0: 2270, 58.0: 2265, 59.0: 2260, 6

In [5]:
# Split the Data
X_train, X_test, y_train, y_test = train_test_split(X_rus, y_rus, test_size=0.2, random_state=0)

In [6]:
# Train GBR
from sklearn import ensemble
params = {'n_estimators': 500, 'max_depth': 6, 
          'learning_rate': 0.01,'verbose': 100}
clf = ensemble.GradientBoostingRegressor(**params)
print('start')
clf.fit(X_train, y_train)

start
      Iter       Train Loss   Remaining Time 
         1      115095.9325            7.85m
         2      112911.6242            7.71m
         3      110770.7826            7.75m
         4      108672.5430            7.59m
         5      106616.0607            7.60m
         6      104600.4160            7.63m
         7      102624.8815            7.65m
         8      100688.6585            7.61m
         9       98790.9653            7.64m
        10       96931.0347            7.61m
        11       95108.1218            7.61m
        12       93321.4825            7.58m
        13       91570.3952            7.55m
        14       89854.1512            7.51m
        15       88172.0500            7.46m
        16       86523.4275            7.44m
        17       84907.6095            7.41m
        18       83323.9382            7.40m
        19       81771.8179            7.40m
        20       80250.4503            7.42m
        21       78759.4861            7.45m
   

       182        8024.2420            5.07m
       183        7965.8285            5.05m
       184        7908.8390            5.03m
       185        7851.7258            5.02m
       186        7796.6184            5.00m
       187        7742.0126            4.99m
       188        7688.5851            4.97m
       189        7635.7265            4.96m
       190        7584.8145            4.94m
       191        7534.8972            4.92m
       192        7485.2349            4.90m
       193        7437.2679            4.89m
       194        7389.3058            4.87m
       195        7342.7655            4.86m
       196        7297.6709            4.84m
       197        7253.3818            4.82m
       198        7209.0207            4.81m
       199        7166.3816            4.79m
       200        7124.7240            4.78m
       201        7083.6875            4.76m
       202        7042.8925            4.75m
       203        7002.4124            4.73m
       204

       365        4978.8980            2.12m
       366        4977.1728            2.10m
       367        4974.7385            2.09m
       368        4972.7930            2.07m
       369        4970.6709            2.06m
       370        4968.5960            2.04m
       371        4966.3388            2.02m
       372        4964.6084            2.01m
       373        4962.5619            1.99m
       374        4960.6454            1.98m
       375        4958.1013            1.96m
       376        4955.9507            1.94m
       377        4954.3594            1.93m
       378        4952.2097            1.91m
       379        4950.0887            1.90m
       380        4948.4244            1.88m
       381        4946.8689            1.86m
       382        4945.1655            1.85m
       383        4943.2291            1.83m
       384        4941.7979            1.82m
       385        4940.3249            1.80m
       386        4938.6692            1.78m
       387

GradientBoostingRegressor(alpha=0.9, criterion='friedman_mse', init=None,
                          learning_rate=0.01, loss='ls', max_depth=6,
                          max_features=None, max_leaf_nodes=None,
                          min_impurity_decrease=0.0, min_impurity_split=None,
                          min_samples_leaf=1, min_samples_split=2,
                          min_weight_fraction_leaf=0.0, n_estimators=500,
                          n_iter_no_change=None, presort='auto',
                          random_state=None, subsample=1.0, tol=0.0001,
                          validation_fraction=0.1, verbose=100,
                          warm_start=False)

In [7]:
from joblib import dump, load
from sklearn.metrics import mean_absolute_error

pred = clf.predict(X_test)
print(mean_absolute_error(pred, y_test))
dump(clf, 'regressor2.joblib') 

52.33680930865866


['regressor1.joblib']

In [22]:
# Load Model and Predict and print metrics
regressor = load('regressor.joblib')
p = regressor.predict(X_test)
print(mean_absolute_error(p, y_test))
print(p[:10])
print(y_test[:10])
from sklearn.metrics import r2_score
r2_score(p, y_test)

[  2.41319049   2.68628135   3.00213487   3.69693804   3.5771524
 123.84047095   3.14612935   3.20980367   3.50713016 128.59656693]
[ 0.  0.  0.  0.  0. 81.  0.  0.  0. 58.]


In [ ]:
from sklearn import ensemble
import matplotlib.pyplot as plt 
from sklearn.naive_bayes import GaussianNB 
from sklearn.datasets import load_digits 
from sklearn.model_selection import learning_curve
from sklearn import ensemble
from sklearn.model_selection import GridSearchCV

print("Start")

def GradientBooster(param_grid):
    estimator = ensemble.GradientBoostingRegressor()
    
    #cv = ShuffleSplit(X_train.shape[0], n_iter=10, test_size=0.2) 

    classifier = GridSearchCV(estimator=estimator, cv=10, param_grid=param_grid, n_jobs=-1, verbose=100) 
    classifier.fit(X_rus, y_rus)
    
    print (classifier.best_estimator_ )
    return classifier.best_estimator_

param_grid={'n_estimators':[500], 
            'learning_rate': [0.1],
            'max_depth':[10], 
            'min_samples_leaf':[1]
           }

#Let's fit GBRT to the digits training dataset by calling the function we just created. 
best_est = GradientBooster(param_grid)



#OK great, so we got back the best estimator parameters as follows:
print ("Best Estimator Parameters")
print ("---------------------------")
print ("n_estimators: %d" %best_est.n_estimators)
print ("max_depth: %d" %best_est.max_depth)
print ("Learning Rate: %.1f" %best_est.learning_rate)
print ("min_samples_leaf: %d" %best_est.min_samples_leaf)
print ("max_features: %.1f" %best_est.max_features)

print()
print ("Train R-squared: %.2f" %best_est.score(X_train,y_train))
"""
def plot_learning_curve(estimator, title, X, y, ylim=None, cv=None, n_jobs=1, train_sizes=np.linspace(.1, 1.0, 5)): 
    plt.figure() 
    plt.title(title) 
    if ylim is not None: 
        plt.ylim(*ylim) 
        plt.xlabel("Training examples") 
        plt.ylabel("Score") 
        train_sizes, train_scores, test_scores = learning_curve( estimator, X, y, cv=cv, n_jobs=n_jobs, train_sizes=train_sizes) 
        train_scores_mean = np.mean(train_scores, axis=1) 
        train_scores_std = np.std(train_scores, axis=1) 
        test_scores_mean = np.mean(test_scores, axis=1) 
        test_scores_std = np.std(test_scores, axis=1) 
        plt.grid() 
        plt.fill_between(train_sizes, train_scores_mean - train_scores_std, train_scores_mean + train_scores_std, alpha=0.1, color="r") 
        plt.fill_between(train_sizes, test_scores_mean - test_scores_std, test_scores_mean + test_scores_std, alpha=0.1, color="g") 
        plt.plot(train_sizes, train_scores_mean, 'o-', color="r", label="Training score") 
        plt.plot(train_sizes, test_scores_mean, 'o-', color="g", label="Cross-validation score") 
        plt.legend(loc="best") 
        return plt"""
"""
estimator = ensemble.GradientBoostingRegressor(n_estimators=best_est.n_estimators, 
                                      max_depth=best_est.max_depth, 
                                      learning_rate=best_est.learning_rate, 
                                      min_samples_leaf=best_est.min_samples_leaf, 
                                      max_features=best_est.max_features,
                                      n_jobs=-1,
                                     verbose = 100) 

estimator.fit(X, y)"""

Start
Fitting 10 folds for each of 1 candidates, totalling 10 fits
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 12 concurrent workers.
Memmapping (shape=(581323, 10), dtype=float64) to new file C:\Users\admin\AppData\Local\Temp\joblib_memmapping_folder_15644_2346536603\15644-2803034264520-d0d84e85f50e496e8c337d8863538e3b.pkl
Memmapping (shape=(581323,), dtype=float64) to new file C:\Users\admin\AppData\Local\Temp\joblib_memmapping_folder_15644_2346536603\15644-2803034264520-685116f82b194b5a8fdf26f23bdd5daa.pkl
Memmapping (shape=(523190,), dtype=int32) to new file C:\Users\admin\AppData\Local\Temp\joblib_memmapping_folder_15644_2346536603\15644-2803034264520-c2d21e35afdd4e62a4e78ad197b42fae.pkl
Pickling array (shape=(58133,), dtype=int32).
Memmapping (shape=(581323, 10), dtype=float64) to old file C:\Users\admin\AppData\Local\Temp\joblib_memmapping_folder_15644_2346536603\15644-2803034264520-d0d84e85f50e496e8c337d8863538e3b.pkl
Memmapping (shape=(581323,), dtype=float64) to old

In [10]:
from sklearn import ensemble

estimator = ensemble.GradientBoostingRegressor(n_estimators=100, 
                                      max_depth=6, 
                                      learning_rate=0.1, 
                                      min_samples_leaf=3, 
                                      max_features=1.0,
                                     verbose = 100) 

estimator.fit(X, y)

      Iter       Train Loss   Remaining Time 
         1       75495.8468            2.58m
         2       61318.0277            2.63m
         3       49833.6919            2.57m
         4       40527.5781            2.54m
         5       32991.4663            2.50m
         6       26886.7316            2.47m
         7       21941.6387            2.46m
         8       17936.2354            2.43m
         9       14688.7802            2.42m
        10       12060.7491            2.40m
        11        9930.6896            2.37m
        12        8205.4544            2.34m
        13        6806.7486            2.32m
        14        5673.0557            2.29m
        15        4755.5161            2.26m
        16        4011.3288            2.23m
        17        3407.6989            2.21m
        18        2919.2306            2.18m
        19        2523.6074            2.16m
        20        2200.4420            2.13m
        21        1940.3042            2.10m
        2

GradientBoostingRegressor(alpha=0.9, criterion='friedman_mse', init=None,
                          learning_rate=0.1, loss='ls', max_depth=6,
                          max_features=1.0, max_leaf_nodes=None,
                          min_impurity_decrease=0.0, min_impurity_split=None,
                          min_samples_leaf=3, min_samples_split=2,
                          min_weight_fraction_leaf=0.0, n_estimators=100,
                          n_iter_no_change=None, presort='auto',
                          random_state=None, subsample=1.0, tol=0.0001,
                          validation_fraction=0.1, verbose=100,
                          warm_start=False)

In [ ]:
from joblib import dump, load
dump(estimator, 'crossvalidation1.joblib')

In [9]:
from joblib import dump, load
from sklearn.metrics import mean_absolute_error
est = load('crossvalidation.joblib')
predictioncv = est.predict(X_test)
print(mean_absolute_error(predictioncv, y_test))

7.870788375532486


In [11]:
print(predictioncv[10:20])
print(y_test[10:20])

[999.98269128 999.98269128 999.98269128 999.98269128 999.98269128
 999.98269128 999.98269128 999.98269128 100.77974751 999.98269128]
[1000. 1000. 1000. 1000. 1000. 1000. 1000. 1000.  151. 1000.]


In [12]:
from sklearn.metrics import r2_score
r2_score(predictioncv, y_test)

0.9924888509832172